StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{59652629D7ACB54E}" {
   Id "CAV-Uniform_BDU_CAV_Blouse_Name"
   Target_en_us "BDU Blouse (7CAV)"
   Target_en_us_edited ""
   Target_fr_fr "Chemise de combat (7CAV)"
   Target_it_it "Giacca da combattimento (7CAV)"
   Target_de_de "BDU Uniformjacke (7CAV)"
   Target_es_es "Chaqueta BDU (7CAV)"
   Target_cs_cz "Bunda BDU (7CAV)"
   Target_pl_pl "Bluza BDU (7CAV)"
   Target_ru_ru "Куртка BDU (7CAV)"
   Target_ja_jp "BDU ブラウス (7CAV)"
   Target_ko_kr "BDU 셔츠 (7CAV)"
   Target_pt_br "Blusa BDU (7CAV)"
   Target_zh_cn "BDU 女式衬衫 (7CAV)"
   Comment "Display name of the US BDU (Battle Dress Uniform) blouse"
   DevNote ""
   Repro ""
   ActorGender NONE
   Terminology NONE
   Status TRANSLATION_DONE
   NonTranslatable 0
   MaxLength 0
   Modified 1482225358
   Author "andre"
   LastChanged "andre"
   Labels {
    1200 0
   }
   ImageLink ""
  }
 }
}